#1. What is a Python library? Why do we use Python libraries?

A Python library is collection of functions/ pre-written  codes which will make  the tasks more efficient and Easy.

We use python libraries to eliminate the writing of code from scratch and python libraries are "reusable"


#2. What is the difference between Numpy array and List?


1 Type of Elements:
  Numpy array has homogenous data structures types in the container.where as List as heterogenous collection of data structures types.
  This allows for more efficient storage and operations for Numpy array.

2 Memory efficency:
  Numpy arrays are more memory efficient, as they store data in a continuous block of memory and have a fixed data type for all elements where as Lists are generally less memory efficient compared to NumPy arrays. This is because lists store additional information, such as the type of each element(heterogenous) and the size of the list.
 
3 Performance:
 NumPy arrays are designed for numerical operations and are more efficient for large-scale numerical computations. NumPy is implemented in C and Fortran, which contributes to its performance. C language has the fastest computation compare to any other programming Language.
 Lists are more flexible but may be slower for numerical computations compared to NumPy arrays.

4 Functionality:
   NumPy provides a wide range of functions and operations for numerical computing, such as element-wise operations, linear algebra, statistical operations, and more. These operations are often faster than equivalent operations on lists.
   Lists provide a variety of built-in methods for general-purpose tasks. However, for numerical operations, these methods may not be as optimized as the functions provided by NumPy.

5  Syntax:
    NumPy introduces its own array object with its own syntax. NumPy arrays can be created using the numpy.array() constructor.
    List syntax is straightforward and part of the core Python language.



#3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]



In [1]:
list1 =([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
import numpy as np
arr = np.array(list1)

In [2]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr.ndim

2

In [18]:
arr.size

12

In [19]:
arr.shape

(3, 4)

#4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

arr

In [23]:
arr[0]

array([1, 2, 3, 4])

#5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [29]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
arr[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
odd_indexed=arr[:, 0:3:2]
odd_indexed 

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [65]:
arr[:,0::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [23]:
np.random.rand(3,3)

array([[0.11041547, 0.02233492, 0.75827883],
       [0.93956185, 0.7270932 , 0.27233025],
       [0.86700807, 0.52801634, 0.46255912]])

In [22]:
np.random.randn(3,3)

array([[ 1.29288723,  0.14000738, -0.04003995],
       [-2.20353086, -0.51665435, -1.46677006],
       [-1.25850524, -1.2890852 ,  1.79816761]])

#9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [24]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr.ndim

2

In [26]:
arr.size

12

In [30]:
# We can increase the dimension of array with out change the size of array
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [31]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr1 =arr.T
arr1

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])



#11. Consider the following matrix:
Matrix A2: [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2: [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [39]:
A = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [58]:
#Perform the following operation using Python:
#1 Index wise multiplication'''
M =A * B
M

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [56]:
#2. Matrix multiplication
# To do Matrix multiplication, the columns of A must be equal rows of B then only the Matrix multiplication is possible
# To do that we need to use Transpose of B to make the coulums of B in to rows of B, for matirx Multiplication possible

A.shape, B.shape

((3, 4), (3, 4))

Here, for matrix multiplication is not possible,  columns of A = 4 !=3 rows of B, In this scenario we can make Transpose of any one Matrix, then we can do Matrix multiplication

In [57]:
A @ B.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [47]:
#3. Add both the matrices
C =A + B
C

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [46]:
#4.Subtract  the matrix B from A
S =A - B
S

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
#5 Divide  the matrices B by A
D = B/A
D


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])



##12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, we can use the byteswap function to swap the byte order of an array. This function is used to swap the byte order of the elements of the array without changing the actual data.

The byteswap function takes an optional parameter called byteorder, which specifies the byte order to which the array should be swapped.

In [67]:
arr1 = arr.byteswap()
arr1

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. If you have a square matrix A, then its inverse, denoted as A^{-1}, is a matrix such that when A is multiplied by its inverse, the result is the identity matrix.

In [85]:
#Example for np.linal.inv:
A = np.array([[1,2],[3,2]])
A

array([[1, 2],
       [3, 2]])

In [86]:
A_inv =np.linalg.inv(a)
A_inv

array([[-0.5 ,  0.5 ],
       [ 0.75, -0.25]])

14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array while maintaining the same data/size. It allows/ used you to reorganize the elements of an array into a different shape without altering their values. The reshaping is done by specifying the desired shape of the output array.
It also helps to increase the dimension without alterating the data/size

In [99]:
# Example for reshape
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
arr.ndim

2

In [98]:
arr4 =arr.reshape(2,2,3)
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr4.ndim

3

15. What is broadcasting in Numpy?


Broadcasting in NumPy is a powerful mechanism that allows for operations between arrays of different shapes and sizes. When performing element-wise operations between two arrays, NumPy automatically broadcasts the smaller array to the shape of the larger one, so they can be combined without explicitly replicating the smaller array.

Broadcasting involves two steps:

Size Compatibility: The dimensions of the arrays are compared element-wise, starting from the rightmost dimensions. Two dimensions are compatible when they are equal or one of them is 1. If these conditions are not met, NumPy raises a ValueError.

Broadcasting: If the dimensions are compatible, NumPy performs broadcasting, which means it virtually replicates the smaller array along the missing dimensions. This is done without actually creating multiple copies of the array in memory, making it memory-efficient.

In [113]:
# Example for broadcasting:
arr 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
arr +10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [109]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [103]:
arr +a

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [116]:
b = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])